Question 1
a. For every element e in a and b, calculate and print whether a[e] > b[e]


In [2]:
import numpy as np
a = np.array([30, 45, 22, 75, 84])
b = np.array([67, 40, 90, 13, 56])
print(a>b)


[False  True False  True  True]


Question 1b
b. Use a binary mask to change all values where a[e] > 30 to be set to 50. 

In [12]:
import numpy as np
a = np.array([30, 45, 22, 75, 84])
b = np.array([67, 40, 90, 13, 56])
print(a)
print(a > 30)
a[a > 30] = 50
print(a)

[30 45 22 75 84]
[False  True False  True  True]


array([30, 50, 22, 50, 50])

Question 2

Given array x = [[5, 2, 6, 1], [3, 4, 7, 2], [8, 1, 2, 9], [3, 4, 2, 6]], calculate the sum of the
highlighted and bolded elements using indexing. 

In [23]:
x = np.array([[5, 2, 6, 1], [3, 4, 7, 2], [8, 1, 2, 9], [3, 4, 2, 6]])
#sum of [0, 2], [3,1]
subset_1 = x[0,2] #6
subset_2 = x[3,1] #4

print(np.sum([subset_1, subset_2]))


10


Question 3

Given array c = [[1, 0], [8, 1]] and array d = [[4, 1], [2, 2]], calculate the dot product of c
and d. 

In [27]:
c = np.array([[1, 0], [8, 1]])
d = np.array([[4, 1], [2, 2]])
print(np.dot(c,d))


[[ 4  1]
 [34 10]]


Question 4

Given array a = [[1, 4], [2, 9], [5, 6]], find the shape and transpose of a. 

In [29]:
 a = np.array([[1, 4], [2, 9], [5, 6]])
 print(a.shape)
 print(a.T)

(3, 2)
[[1 2 5]
 [4 9 6]]


Question 5

Given array x = [[1, 2], [3, 4]] and array y = [[5, 6], [7, 8], [9, 0]], stack the arrays in
sequence vertically.

In [31]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8], [9, 0]])
print(np.vstack([x,y]))


[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


Question 6

Calculate the area of x2 + y
2 ≤ 1 by uniformly sampling x in [-1,1] and y in [-1,1].

In [35]:
trial = 100000
x = np.random.uniform(-1, 1, size = trial)
y = np.random.uniform(-1, 1, size = trial)
z = x ** 2 + y ** 2
prob = np.sum(z<=1) / trial
area = prob *4
print(area)

3.13932


Question 7

Calculate the probability that x
2 + y2 ≤ 1 if x and y are two standard Gaussian
distribution variables.


In [36]:
trial = 100000
x = np.random.normal(trial)
y = np.random.normal(trial)
z = x ** 2 + y ** 2
prob = np.sum(z<=1) / trial
print(prob)

0.39561


Question 8

Calculate the probability that the sum of three dices is larger than 10 if you randomly roll
the three dices.

In [43]:

trial = 500000
sample_data = np.random.randint(1,7, size = trial * 3)
rolls = sample_data.reshape(trial, 3)
sum_of_rolls = rolls.sum(-1)
how_many_larger = np.sum(sum_of_rolls > 10)
prob = how_many_larger / trial
print(prob)

0.499184
